/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => BaseBoardPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian8 = require("obsidian");

// src/kanban-view.ts
var import_obsidian7 = require("obsidian");

// src/drag-drop.ts
var CARD_MIME = "application/x-kanban-card";
var COLUMN_MIME = "application/x-kanban-column";
var DragDropManager = class {
  constructor(app, callbacks) {
    this.boardEl = null;
    this.draggedEl = null;
    this.placeholderEl = null;
    this.dragType = null;
    /** True after a successful card drop — prevents visual cleanup before re-render */
    this.cardDropped = false;
    /** Height of the dragged card, used to size the placeholder */
    this.draggedCardHeight = 0;
    /** Other selected card elements dimmed during multi-drag */
    this.multiDragEls = [];
    /** Auto-scroll state */
    this.autoScrollRAF = null;
    this.autoScrollSpeed = 0;
    // horizontal (boardEl)
    this.autoScrollVerticalSpeed = 0;
    // vertical (active cards container)
    this.autoScrollVerticalEl = null;
    this.app = app;
    this.callbacks = callbacks;
    this.boundHandlers = {
      dragStart: this.onDragStart.bind(this),
      dragOver: this.onDragOver.bind(this),
      dragEnd: this.onDragEnd.bind(this),
      drop: (e) => {
        void this.onDrop(e);
      }
    };
  }
  initBoard(boardEl) {
    this.teardownBoard();
    this.boardEl = boardEl;
    boardEl.addEventListener("dragstart", this.boundHandlers.dragStart);
    boardEl.addEventListener("dragover", this.boundHandlers.dragOver);
    boardEl.addEventListener("dragend", this.boundHandlers.dragEnd);
    boardEl.addEventListener("drop", this.boundHandlers.drop);
  }
  destroy() {
    this.teardownBoard();
  }
  teardownBoard() {
    if (!this.boardEl) return;
    this.boardEl.removeEventListener("dragstart", this.boundHandlers.dragStart);
    this.boardEl.removeEventListener("dragover", this.boundHandlers.dragOver);
    this.boardEl.removeEventListener("dragend", this.boundHandlers.dragEnd);
    this.boardEl.removeEventListener("drop", this.boundHandlers.drop);
    this.removePlaceholder();
    this.boardEl = null;
  }
  // ---------------------------------------------------------------------------
  //  Drag Start
  // ---------------------------------------------------------------------------
  onDragStart(e) {
    var _a, _b, _c;
    if (!e.dataTransfer) return;
    const headerEl = e.target.closest(
      ".base-board-column-header"
    );
    if (headerEl) {
      const target = e.target;
      const isInteractive = target.closest(
        ".base-board-column-title, .base-board-column-count, .base-board-column-delete, input, button"
      );
      if (isInteractive) return;
      const columnEl = headerEl.closest(".base-board-column");
      if (!(columnEl instanceof HTMLElement)) return;
      this.dragType = "column";
      this.draggedEl = columnEl;
      e.dataTransfer.effectAllowed = "move";
      e.dataTransfer.setData(COLUMN_MIME, (_a = columnEl.dataset.columnName) != null ? _a : "");
      const headerRect = headerEl.getBoundingClientRect();
      e.dataTransfer.setDragImage(
        headerEl,
        e.clientX - headerRect.left,
        e.clientY - headerRect.top
      );
      window.requestAnimationFrame(() => {
        var _a2;
        this.placeholderEl = this.boardEl.createDiv();
        this.placeholderEl.className = "base-board-column-placeholder";
        (_a2 = columnEl.parentElement) == null ? void 0 : _a2.insertBefore(this.placeholderEl, columnEl);
        columnEl.addClass("base-board-column--dragging");
      });
      return;
    }
    const cardEl = e.target.closest(".base-board-card");
    if (!(cardEl instanceof HTMLElement)) return;
    this.dragType = "card";
    this.draggedEl = cardEl;
    const cardRect = cardEl.getBoundingClientRect();
    this.draggedCardHeight = cardRect.height;
    e.dataTransfer.effectAllowed = "move";
    e.dataTransfer.setData(CARD_MIME, (_b = cardEl.dataset.filePath) != null ? _b : "");
    const selectedCards = this.callbacks.getSelectedCards();
    const filePath = (_c = cardEl.dataset.filePath) != null ? _c : "";
    const isMultiDrag = selectedCards.size > 1 && selectedCards.has(filePath);
    const dragCount = isMultiDrag ? selectedCards.size : 1;
    const PAD = 20;
    const ghostWrapper = this.boardEl.createDiv();
    ghostWrapper.style.cssText = `
      position: fixed;
      top: -9999px;
      left: -9999px;
      padding: ${PAD}px;
      pointer-events: none;
      z-index: 9999;
    `;
    if (isMultiDrag) {
      const stackContainer = ghostWrapper.createDiv();
      stackContainer.style.cssText = `
        position: relative;
        width: ${cardRect.width}px;
      `;
      const compStyles = getComputedStyle(cardEl);
      const cardBg = compStyles.backgroundColor || "#1e1e2e";
      const borderColor = compStyles.borderColor || "#383850";
      const accentColor = getComputedStyle(activeDocument.body).getPropertyValue(
        "--interactive-accent"
      ) || "#7c3aed";
      const layerCount = Math.min(dragCount - 1, 2);
      for (let i = layerCount; i >= 1; i--) {
        const layer = stackContainer.createDiv();
        layer.style.cssText = `
          position: absolute;
          top: ${i * 6}px;
          left: ${i * 4}px;
          width: 100%;
          height: ${cardRect.height}px;
          background: ${cardBg};
          border: 1px solid ${borderColor};
          border-radius: 6px;
          opacity: ${0.6 - i * 0.15};
          box-shadow: 0 2px 6px rgba(0,0,0,0.1);
        `;
      }
      const ghost = cardEl.cloneNode(true);
      ghost.style.cssText = `
        position: relative;
        width: ${cardRect.width}px;
        transform: rotate(2deg);
        box-shadow: 0 8px 24px rgba(0, 0, 0, 0.22);
        opacity: 0.95;
        border-radius: 6px;
        background: ${cardBg};
        border: 1px solid ${borderColor};
      `;
      ghost.classList.remove("base-board-card--selected");
      stackContainer.appendChild(ghost);
      const badge = stackContainer.createDiv();
      badge.textContent = String(dragCount);
      badge.style.cssText = `
        position: absolute;
        top: -10px;
        right: -10px;
        min-width: 24px;
        height: 24px;
        line-height: 24px;
        text-align: center;
        font-size: 13px;
        font-weight: 700;
        color: #fff;
        background: ${accentColor};
        border-radius: 12px;
        padding: 0 6px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.3);
        z-index: 1;
      `;
    } else {
      const ghost = cardEl.cloneNode(true);
      ghost.style.cssText = `
        width: ${cardRect.width}px;
        transform: rotate(3deg);
        box-shadow: 0 8px 24px rgba(0, 0, 0, 0.18);
        opacity: 0.85;
        border-radius: var(--radius-s, 6px);
      `;
      ghostWrapper.appendChild(ghost);
    }
    ghostWrapper.remove();
    activeDocument.body.appendChild(ghostWrapper);
    void ghostWrapper.getBoundingClientRect();
    e.dataTransfer.setDragImage(
      ghostWrapper,
      e.clientX - cardRect.left + PAD,
      e.clientY - cardRect.top + PAD
    );
    window.requestAnimationFrame(() => {
      var _a2;
      ghostWrapper.remove();
      this.placeholderEl = this.boardEl.createDiv();
      this.placeholderEl.className = "base-board-card-placeholder";
      this.placeholderEl.style.height = `${this.draggedCardHeight}px`;
      (_a2 = cardEl.parentElement) == null ? void 0 : _a2.insertBefore(this.placeholderEl, cardEl);
      cardEl.addClass("base-board-card--dragging");
      if (isMultiDrag && this.boardEl) {
        this.multiDragEls = Array.from(
          this.boardEl.querySelectorAll(".base-board-card")
        ).filter(
          (el) => {
            var _a3;
            return el !== cardEl && selectedCards.has((_a3 = el.dataset.filePath) != null ? _a3 : "");
          }
        );
        for (const el of this.multiDragEls) {
          el.addClass("base-board-card--drag-ghost");
        }
      }
    });
  }
  // ---------------------------------------------------------------------------
  //  Drag Over
  // ---------------------------------------------------------------------------
  onDragOver(e) {
    e.preventDefault();
    if (!e.dataTransfer) return;
    e.dataTransfer.dropEffect = "move";
    this.updateAutoScroll(e.clientX, e.clientY, e.target);
    if (this.dragType === "column") {
      this.handleColumnDragOver(e);
    } else if (this.dragType === "card") {
      this.handleCardDragOver(e);
    }
  }
  handleCardDragOver(e) {
    const closestCardsContainer = e.target.closest(
      ".base-board-cards"
    );
    let cardsContainer = closestCardsContainer instanceof HTMLElement ? closestCardsContainer : null;
    if (!cardsContainer) {
      const columnEl = e.target.closest(".base-board-column");
      if (columnEl instanceof HTMLElement) {
        const qc = columnEl.querySelector(".base-board-cards");
        if (qc instanceof HTMLElement) {
          cardsContainer = qc;
        }
      }
    }
    const hoveredColumn = cardsContainer == null ? void 0 : cardsContainer.closest(
      ".base-board-column"
    );
    if (this.boardEl) {
      const allColumns = this.boardEl.querySelectorAll(".base-board-column");
      allColumns.forEach((col) => {
        if (col === hoveredColumn) {
          col.classList.add("base-board-column--drag-over");
        } else {
          col.classList.remove("base-board-column--drag-over");
        }
      });
    }
    if (!cardsContainer) {
      this.removePlaceholder();
      return;
    }
    if (!this.placeholderEl) {
      this.placeholderEl = this.boardEl.createDiv();
      this.placeholderEl.className = "base-board-card-placeholder";
      this.placeholderEl.style.height = `${this.draggedCardHeight}px`;
    }
    const afterElement = this.getDragAfterElement(
      cardsContainer,
      ".base-board-card:not(.base-board-card--dragging)",
      e.clientY,
      "vertical"
    );
    if (afterElement) {
      cardsContainer.insertBefore(this.placeholderEl, afterElement);
    } else {
      cardsContainer.appendChild(this.placeholderEl);
    }
  }
  handleColumnDragOver(e) {
    var _a;
    if (!this.boardEl) return;
    if (!this.placeholderEl) {
      this.placeholderEl = this.boardEl.createDiv();
      this.placeholderEl.className = "base-board-column-placeholder";
    }
    const afterElement = this.getDragAfterElement(
      this.boardEl,
      ".base-board-column:not(.base-board-column--dragging)",
      e.clientX,
      "horizontal"
    );
    const desiredNext = (_a = afterElement != null ? afterElement : this.boardEl.querySelector(".base-board-add-column-btn")) != null ? _a : null;
    if (this.placeholderEl.nextElementSibling === desiredNext && this.placeholderEl.parentElement === this.boardEl) {
      return;
    }
    if (afterElement) {
      this.boardEl.insertBefore(this.placeholderEl, afterElement);
    } else {
      const addBtn = this.boardEl.querySelector(".base-board-add-column-btn");
      if (addBtn) {
        this.boardEl.insertBefore(this.placeholderEl, addBtn);
      } else {
        this.boardEl.appendChild(this.placeholderEl);
      }
    }
  }
  // ---------------------------------------------------------------------------
  //  Drag End
  // ---------------------------------------------------------------------------
  updateAutoScroll(clientX, clientY, target) {
    const H_ZONE = 80;
    const V_ZONE = 60;
    const MAX_SPEED = 12;
    if (this.boardEl) {
      const rect = this.boardEl.getBoundingClientRect();
      const relX = clientX - rect.left;
      if (relX < H_ZONE) {
        this.autoScrollSpeed = -MAX_SPEED * (1 - relX / H_ZONE);
      } else if (relX > rect.width - H_ZONE) {
        this.autoScrollSpeed = MAX_SPEED * (1 - (rect.width - relX) / H_ZONE);
      } else {
        this.autoScrollSpeed = 0;
      }
    }
    const cardsEl = target.closest(".base-board-cards");
    if (cardsEl) {
      const rect = cardsEl.getBoundingClientRect();
      const relY = clientY - rect.top;
      if (relY < V_ZONE) {
        this.autoScrollVerticalSpeed = -MAX_SPEED * (1 - relY / V_ZONE);
        this.autoScrollVerticalEl = cardsEl;
      } else if (relY > rect.height - V_ZONE) {
        this.autoScrollVerticalSpeed = MAX_SPEED * (1 - (rect.height - relY) / V_ZONE);
        this.autoScrollVerticalEl = cardsEl;
      } else {
        this.autoScrollVerticalSpeed = 0;
        this.autoScrollVerticalEl = null;
      }
    } else {
      this.autoScrollVerticalSpeed = 0;
      this.autoScrollVerticalEl = null;
    }
    const needsScroll = this.autoScrollSpeed !== 0 || this.autoScrollVerticalSpeed !== 0;
    if (needsScroll && this.autoScrollRAF === null) {
      const tick = () => {
        if (this.autoScrollSpeed === 0 && this.autoScrollVerticalSpeed === 0) {
          this.autoScrollRAF = null;
          return;
        }
        if (this.boardEl && this.autoScrollSpeed !== 0) {
          this.boardEl.scrollLeft += this.autoScrollSpeed;
        }
        if (this.autoScrollVerticalEl && this.autoScrollVerticalSpeed !== 0) {
          this.autoScrollVerticalEl.scrollTop += this.autoScrollVerticalSpeed;
        }
        this.autoScrollRAF = window.requestAnimationFrame(tick);
      };
      this.autoScrollRAF = window.requestAnimationFrame(tick);
    } else if (!needsScroll && this.autoScrollRAF !== null) {
      cancelAnimationFrame(this.autoScrollRAF);
      this.autoScrollRAF = null;
    }
  }
  onDragEnd() {
    if (this.autoScrollRAF !== null) {
      cancelAnimationFrame(this.autoScrollRAF);
      this.autoScrollRAF = null;
    }
    this.autoScrollSpeed = 0;
    this.autoScrollVerticalSpeed = 0;
    this.autoScrollVerticalEl = null;
    for (const el of this.multiDragEls) {
      el.removeClass("base-board-card--drag-ghost");
    }
    this.multiDragEls = [];
    if (this.cardDropped) {
      this.cardDropped = false;
    } else if (this.draggedEl) {
      this.draggedEl.removeClass("base-board-card--dragging");
      this.draggedEl.removeClass("base-board-column--dragging");
      this.removePlaceholder();
    }
    this.draggedEl = null;
    if (this.boardEl) {
      this.boardEl.querySelectorAll(".base-board-column--drag-over").forEach((col) => col.classList.remove("base-board-column--drag-over"));
    }
    this.dragType = null;
  }
  // ---------------------------------------------------------------------------
  //  Drop
  // ---------------------------------------------------------------------------
  async onDrop(e) {
    e.preventDefault();
    if (this.dragType === "column") {
      this.handleColumnDrop(e);
      this.onDragEnd();
    } else if (this.dragType === "card") {
      const success = await this.handleCardDrop(e);
      this.cardDropped = success;
    }
  }
  handleColumnDrop(e) {
    var _a;
    if (!this.boardEl) return;
    const draggedColumnName = (_a = e.dataTransfer) == null ? void 0 : _a.getData(COLUMN_MIME);
    if (!draggedColumnName) return;
    const orderedNames = [];
    for (const child of Array.from(this.boardEl.children)) {
      if (child === this.placeholderEl) {
        orderedNames.push(draggedColumnName);
      } else if (child.classList.contains("base-board-column") && !child.classList.contains("base-board-column--dragging")) {
        const name = child.dataset.columnName;
        if (name && name !== draggedColumnName) {
          orderedNames.push(name);
        }
      }
    }
    if (!orderedNames.includes(draggedColumnName)) {
      orderedNames.push(draggedColumnName);
    }
    this.callbacks.onColumnReorder(orderedNames);
  }
  async handleCardDrop(e) {
    var _a;
    const filePath = (_a = e.dataTransfer) == null ? void 0 : _a.getData(CARD_MIME);
    if (!filePath) return false;
    const columnEl = e.target.closest(".base-board-column");
    if (!(columnEl instanceof HTMLElement)) return false;
    const targetColumnName = columnEl.dataset.columnName;
    if (!targetColumnName) return false;
    const cardsContainer = columnEl.querySelector(".base-board-cards");
    const orderedPaths = [];
    if (cardsContainer) {
      for (const child of Array.from(cardsContainer.children)) {
        if (child === this.placeholderEl) {
          orderedPaths.push(filePath);
        } else if (child.classList.contains("base-board-card") && !child.classList.contains("base-board-card--dragging")) {
          const path = child.dataset.filePath;
          if (path && path !== filePath) {
            orderedPaths.push(path);
          }
        }
      }
      if (!orderedPaths.includes(filePath)) {
        orderedPaths.push(filePath);
      }
    }
    await this.callbacks.onCardDrop(filePath, targetColumnName, orderedPaths);
    return true;
  }
  // ---------------------------------------------------------------------------
  //  Utilities
  // ---------------------------------------------------------------------------
  /**
   * Find the child in `container` matching `selector` that the dragged
   * element should be inserted *before*.
   */
  getDragAfterElement(container, selector, cursorPos, axis) {
    const els = Array.from(container.querySelectorAll(selector));
    let closest = null;
    let closestOffset = Number.NEGATIVE_INFINITY;
    for (const child of els) {
      const box = child.getBoundingClientRect();
      const offset = axis === "vertical" ? cursorPos - box.top - box.height / 2 : cursorPos - box.left - box.width / 2;
      if (offset < 0 && offset > closestOffset) {
        closestOffset = offset;
        closest = child;
      }
    }
    return closest;
  }
  removePlaceholder() {
    if (this.placeholderEl) {
      this.placeholderEl.remove();
      this.placeholderEl = null;
    }
  }
};

// src/column.ts
var import_obsidian4 = require("obsidian");

// src/modals.ts
var import_obsidian = require("obsidian");
var InputModal = class extends import_obsidian.Modal {
  constructor(app, title, placeholder, onSubmit, initialValue) {
    super(app);
    this.value = "";
    this.title = title;
    this.placeholder = placeholder;
    this.onSubmit = onSubmit;
    if (initialValue) {
      this.value = initialValue;
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: this.title });
    new import_obsidian.Setting(contentEl).setName("Name").addText((text) => {
      text.setPlaceholder(this.placeholder);
      if (this.value) {
        text.setValue(this.value);
      }
      text.onChange((v) => this.value = v);
      window.setTimeout(() => {
        text.inputEl.focus();
        text.inputEl.addEventListener("keydown", (e) => {
          if (e.key === "Enter") {
            e.preventDefault();
            this.submit();
          }
        });
      }, 50);
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Add").setCta().onClick(() => this.submit());
    });
  }
  submit() {
    const trimmed = this.value.trim();
    if (trimmed) {
      this.onSubmit(trimmed);
    }
    this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var WipLimitModal = class extends import_obsidian.Modal {
  constructor(app, columnName, currentLimit, onSubmit) {
    super(app);
    this.value = "";
    this.columnName = columnName;
    this.currentLimit = currentLimit;
    this.onSubmit = onSubmit;
    this.value = currentLimit !== null ? String(currentLimit) : "";
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: `WIP limit: ${this.columnName}` });
    new import_obsidian.Setting(contentEl).setName("Maximum cards").setDesc("Leave empty to remove the limit").addText((text) => {
      text.setPlaceholder("E.g. 5");
      if (this.currentLimit !== null) {
        text.setValue(String(this.currentLimit));
      }
      text.onChange((v) => this.value = v);
      window.setTimeout(() => {
        text.inputEl.focus();
        text.inputEl.addEventListener("keydown", (e) => {
          if (e.key === "Enter") {
            e.preventDefault();
            this.submit();
          }
        });
      }, 50);
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Save").setCta().onClick(() => this.submit());
    });
    if (this.currentLimit !== null) {
      new import_obsidian.Setting(contentEl).addButton((btn) => {
        btn.setButtonText("Remove limit").onClick(() => {
          this.onSubmit(null);
          this.close();
        });
      });
    }
  }
  submit() {
    const trimmed = this.value.trim();
    if (trimmed === "") {
      this.onSubmit(null);
    } else {
      const num = parseInt(trimmed, 10);
      if (isNaN(num) || num <= 0) {
        new import_obsidian.Notice("Wip limit must be a positive number.");
        return;
      }
      this.onSubmit(num);
    }
    this.close();
  }
  onClose() {
    this.contentEl.empty();
  }
};
var CreateBoardModal = class extends import_obsidian.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.config = {
      name: "",
      folder: "",
      groupBy: "status"
    };
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Create new board" });
    new import_obsidian.Setting(contentEl).setName("Board name").addText((text) => {
      text.setPlaceholder("My new board");
      text.onChange((v) => {
        this.config.name = v;
        if (!folderManuallyEdited) {
          folderInput.setValue(v);
          this.config.folder = v;
        }
      });
      window.setTimeout(() => text.inputEl.focus(), 50);
    });
    let folderManuallyEdited = false;
    let folderInput;
    new import_obsidian.Setting(contentEl).setName("Folder").setDesc("Where to create the board and its task files").addText((text) => {
      folderInput = text;
      text.setPlaceholder("Projects/alpha");
      text.onChange((v) => {
        this.config.folder = v;
        folderManuallyEdited = true;
      });
    });
    new import_obsidian.Setting(contentEl).setName("Group by property").setDesc("The frontmatter property used for columns").addText((text) => {
      text.setValue("status");
      text.setPlaceholder("Status");
      text.onChange((v) => this.config.groupBy = v || "status");
    });
    new import_obsidian.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Create").setCta().onClick(() => this.submit());
    });
    contentEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.submit();
      }
    });
  }
  submit() {
    const name = this.config.name.trim();
    if (!name) {
      new import_obsidian.Notice("Please enter a board name.");
      return;
    }
    this.config.name = name;
    this.config.folder = this.config.folder.trim() || name;
    this.config.groupBy = this.config.groupBy.trim() || "status";
    this.close();
    this.onSubmit(this.config);
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/constants.ts
var NO_VALUE_COLUMN = "(No value)";
var ORDER_PROPERTY = "kanban_order";
var CONFIG_KEY_COLUMNS = "boardColumns";
var CONFIG_KEY_TAG_COLORS = "tagColors";
var CONFIG_KEY_OPEN_BEHAVIOR = "cardOpenBehavior";
var CONFIG_KEY_COLUMN_COLORS = "columnColors";
var CONFIG_KEY_WIP_LIMITS = "wipLimits";
var CONFIG_KEY_COVER_PROPERTY = "cardCoverProperty";
var UNSAFE_FILENAME_CHARS = /[\\/:*?"<>|]/g;
function sanitizeFilename(name) {
  return name.replace(UNSAFE_FILENAME_CHARS, "");
}

// src/tags.ts
var import_obsidian3 = require("obsidian");

// src/tag-edit-modal.ts
var import_obsidian2 = require("obsidian");

// src/color-utils.ts
var relativeLuminance = (colorCode) => {
  if (!colorCode) {
    throw new Error("Please provide a hex color code");
  }
  const hexRegex = /^#([A-Fa-f0-9]{3}){1,2}$/;
  const isValidHex = hexRegex.test(colorCode);
  if (!isValidHex) {
    throw new Error("Please provide a valid hex code");
  }
  colorCode = colorCode.length === 4 ? colorCode.replace(/^#(.)(.)(.)$/, "#$1$1$2$2$3$3") : colorCode;
  const hex = colorCode.substring(1);
  const [red, green, blue] = [0, 2, 4].map(
    (startIndex) => Number.parseInt(hex.substring(startIndex, startIndex + 2), 16)
  );
  const lum = (0.2126 * red + 0.7152 * green + 0.0722 * blue) / 255;
  return lum < 0.7 ? "dark" : "light";
};

// src/tag-edit-modal.ts
var TagEditModal = class extends import_obsidian2.Modal {
  constructor(app, tags, tagsManager, onSubmit) {
    super(app);
    this.tags = [...tags];
    this.tagsManager = tagsManager;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    this.titleEl.setText("Edit tags");
    this.contentEl.createEl("p", {
      text: "Type a tag and press enter or comma. Press backspace to remove.",
      cls: "setting-item-description"
    });
    this.inputContainerEl = this.contentEl.createDiv({
      cls: "base-board-tag-input-container"
    });
    this.inputEl = this.inputContainerEl.createEl("input", {
      type: "text",
      cls: "base-board-tag-input",
      placeholder: "Add tag..."
    });
    this.inputContainerEl.addEventListener("click", () => {
      this.inputEl.focus();
    });
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === ",") {
        e.preventDefault();
        const val = this.inputEl.value.trim();
        if (val && !this.tags.includes(val)) {
          this.tags.push(val);
        }
        this.inputEl.value = "";
        this.renderTags();
      } else if (e.key === "Backspace" && this.inputEl.value === "") {
        if (this.tags.length > 0) {
          this.tags.pop();
          this.renderTags();
        }
      }
    });
    this.renderTags();
    const actionsContainer = this.contentEl.createDiv({
      cls: "base-board-modal-actions-right"
    });
    new import_obsidian2.Setting(actionsContainer).addButton((btn) => {
      btn.setButtonText("Save").setCta().onClick(() => {
        const val = this.inputEl.value.trim();
        if (val && !this.tags.includes(val)) {
          this.tags.push(val);
        }
        this.close();
        this.onSubmit(this.tags);
      });
    });
    window.setTimeout(() => this.inputEl.focus(), 50);
  }
  renderTags() {
    const existingTags = this.inputContainerEl.querySelectorAll(
      ".base-board-tag-chip"
    );
    existingTags.forEach((el) => el.remove());
    this.tags.forEach((tag) => {
      const chipEl = this.inputContainerEl.createDiv({
        cls: "base-board-tag-chip"
      });
      chipEl.createSpan({ text: tag, cls: "base-board-tag-chip-text" });
      const color = this.tagsManager.getColorForTag(tag);
      if (color) {
        chipEl.style.setProperty("--tag-color", color);
        if (relativeLuminance(color) === "dark") {
          chipEl.addClass("base-board-tag-chip-light");
        } else {
          chipEl.addClass("base-board-tag-chip-dark");
        }
      }
      const removeBtn = chipEl.createSpan({
        cls: "base-board-tag-chip-remove"
      });
      (0, import_obsidian2.setIcon)(removeBtn, "lucide-x");
      removeBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.tags = this.tags.filter((t) => t !== tag);
        this.renderTags();
        this.inputEl.focus();
      });
      this.inputContainerEl.insertBefore(chipEl, this.inputEl);
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/tags.ts
var Tags = class {
  constructor(view) {
    this.activeFilters = /* @__PURE__ */ new Set();
    this.view = view;
  }
  getColors() {
    var _a;
    const raw = (_a = this.view.config) == null ? void 0 : _a.get(CONFIG_KEY_TAG_COLORS);
    return raw && typeof raw === "object" ? raw : {};
  }
  getDeterministicColor(tag) {
    const DEFAULT_COLORS = [
      "#f87168",
      // Red
      "#fbbc04",
      // Orange
      "#fcc934",
      // Yellow
      "#34a853",
      // Green
      "#4285f4",
      // Blue
      "#a142f4",
      // Purple
      "#f442a1",
      // Pink
      "#20c997",
      // Teal
      "#fd7e14",
      // Orange
      "#6f42c1"
      // Indigo
    ];
    let hash = 0;
    for (let i = 0; i < tag.length; i++) {
      hash = tag.charCodeAt(i) + ((hash << 5) - hash);
    }
    return DEFAULT_COLORS[Math.abs(hash) % DEFAULT_COLORS.length] || DEFAULT_COLORS[0];
  }
  getColorForTag(tag) {
    const customColors = this.getColors();
    return customColors[tag] || this.getDeterministicColor(tag);
  }
  setColor(tag, color) {
    var _a;
    const colors = this.getColors();
    if (color) {
      colors[tag] = color;
    } else {
      delete colors[tag];
    }
    (_a = this.view.config) == null ? void 0 : _a.set(CONFIG_KEY_TAG_COLORS, colors);
    this.view.scheduleRender();
  }
  extractTagsFromFile(file) {
    var _a, _b, _c;
    const cache = this.view.app.metadataCache.getFileCache(file);
    const tags = (_c = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.tags) != null ? _c : (_b = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _b.tag;
    let fileTags = [];
    if (Array.isArray(tags)) {
      fileTags = tags.filter((t) => typeof t === "string");
    } else if (typeof tags === "string") {
      fileTags = tags.split(",").map((t) => t.trim()).filter((t) => t);
    }
    return fileTags.map((t) => t.startsWith("#") ? t.slice(1) : t);
  }
  promptEditTags(file) {
    const currentTags = this.extractTagsFromFile(file);
    new TagEditModal(this.view.app, currentTags, this, (newTags) => {
      void this.view.app.fileManager.processFrontMatter(
        file,
        (fm) => {
          if (newTags.length === 0) {
            delete fm.tags;
            delete fm.tag;
          } else {
            fm.tags = newTags;
          }
        }
      );
    }).open();
  }
  renderFilterBar(container) {
    const allTags = /* @__PURE__ */ new Set();
    for (const group of this.view.currentGroups) {
      for (const entry of group.entries) {
        if (entry.file instanceof import_obsidian3.TFile) {
          const fileTags = this.extractTagsFromFile(entry.file);
          fileTags.forEach((t) => allTags.add(t));
        }
      }
    }
    if (allTags.size === 0 && this.activeFilters.size === 0) {
      return;
    }
    const boardEl = container.querySelector(".base-board-board");
    if (!boardEl) return;
    const barEl = container.createDiv({ cls: "base-board-filter-bar" });
    container.insertBefore(barEl, boardEl);
    const titleEl = barEl.createSpan({
      cls: "base-board-filter-title",
      text: "Filters:"
    });
    (0, import_obsidian3.setIcon)(titleEl, "lucide-filter");
    const tagsArray = Array.from(allTags).sort();
    for (const activeTag of this.activeFilters) {
      if (!allTags.has(activeTag)) tagsArray.push(activeTag);
    }
    for (const tag of tagsArray) {
      const pill = barEl.createSpan({ cls: "base-board-filter-pill" });
      pill.textContent = tag;
      const tagColor = this.getColorForTag(tag);
      if (tagColor) {
        pill.style.setProperty("--tag-color", tagColor);
        if (relativeLuminance(tagColor) === "dark") {
          pill.addClass("base-board-filter-pill-light");
        } else {
          pill.addClass("base-board-filter-pill-dark");
        }
      }
      if (this.activeFilters.has(tag)) {
        pill.addClass("is-active");
      }
      (0, import_obsidian3.setTooltip)(pill, "Click to filter \xB7 Right-click to change color");
      pill.addEventListener("contextmenu", (e) => {
        e.preventDefault();
        new ColorPickerModal(
          this.view.app,
          tag,
          tagColor,
          (color) => this.setColor(tag, color)
        ).open();
      });
      pill.addEventListener("click", () => {
        if (this.activeFilters.has(tag)) {
          this.activeFilters.delete(tag);
        } else {
          this.activeFilters.add(tag);
        }
        this.view.scheduleRender();
      });
    }
    if (this.activeFilters.size > 0) {
      const clearBtn = barEl.createSpan({
        cls: "base-board-filter-clear",
        text: "Clear"
      });
      clearBtn.addEventListener("click", () => {
        this.activeFilters.clear();
        this.view.scheduleRender();
      });
    }
  }
};
var ColorPickerModal = class extends import_obsidian3.Modal {
  constructor(app, tag, currentColor, onChange) {
    super(app);
    this.tag = tag;
    this.currentColor = currentColor;
    this.onChange = onChange;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h3", { text: `Color for "${this.tag}"` });
    new import_obsidian3.Setting(contentEl).setName("Tag color").addColorPicker((color) => {
      color.setValue(this.currentColor);
      color.onChange((value) => {
        this.currentColor = value;
        this.onChange(value);
      });
    });
    new import_obsidian3.Setting(contentEl).addButton((btn) => {
      btn.setButtonText("Reset to default").onClick(() => {
        this.onChange("");
        this.close();
      });
      btn.buttonEl.classList.add("mod-warning");
    }).addButton((btn) => {
      btn.setButtonText("Done").setCta().onClick(() => this.close());
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/column.ts
var ColumnManager = class {
  constructor(view) {
    this.view = view;
  }
  renderColumn(boardEl, columnName, group, columnIndex) {
    const isNoValue = columnName === NO_VALUE_COLUMN;
    const entries = group ? group.entries : [];
    const sorted = [...entries].sort((a, b) => {
      var _a, _b, _c, _d;
      const pathA = (_b = (_a = a.file) == null ? void 0 : _a.path) != null ? _b : "";
      const pathB = (_d = (_c = b.file) == null ? void 0 : _c.path) != null ? _d : "";
      return this.view.getFileOrder(pathA) - this.view.getFileOrder(pathB);
    });
    const activeFilters = this.view.tags.activeFilters;
    const visibleCards = activeFilters.size > 0 ? sorted.filter((entry) => {
      const file = entry.file;
      if (!(file instanceof import_obsidian4.TFile)) return false;
      const fileTags = this.view.tags.extractTagsFromFile(file);
      return Array.from(activeFilters).some(
        (filter) => fileTags.includes(filter)
      );
    }) : sorted;
    const columnEl = boardEl.createDiv({ cls: "base-board-column" });
    columnEl.dataset.columnName = columnName;
    columnEl.dataset.columnIndex = String(columnIndex);
    const wipLimit = this.view.getWipLimit(columnName);
    if (wipLimit !== null && entries.length > wipLimit) {
      columnEl.addClass("base-board-column--wip-overflow");
    }
    const columnColor = this.view.getColumnColor(columnName);
    if (columnColor) {
      columnEl.style.setProperty("--column-color", columnColor);
      const accentEl = columnEl.createDiv({ cls: "base-board-column-accent" });
      accentEl.style.backgroundColor = columnColor;
    }
    const headerEl = columnEl.createDiv({ cls: "base-board-column-header" });
    headerEl.setAttr("draggable", "true");
    const dragHandle = headerEl.createDiv({
      cls: "base-board-column-drag-handle"
    });
    (0, import_obsidian4.setIcon)(dragHandle, "grip-vertical");
    const titleEl = headerEl.createSpan({
      text: columnName,
      cls: "base-board-column-title"
    });
    if (isNoValue) {
      titleEl.addClass("base-board-no-value-title");
    }
    const countText = wipLimit !== null ? `${entries.length} / ${wipLimit}` : String(entries.length);
    const countEl = headerEl.createSpan({
      text: countText,
      cls: "base-board-column-count"
    });
    headerEl.createDiv({ cls: "base-board-header-spacer" });
    let addCardHeaderBtn = null;
    if (!isNoValue) {
      addCardHeaderBtn = headerEl.createDiv({
        cls: "base-board-column-add-card"
      });
      (0, import_obsidian4.setIcon)(addCardHeaderBtn, "plus");
      addCardHeaderBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        this.view.cardManager.startInlineCardCreation(
          addCardHeaderBtn,
          columnName,
          sorted.length
        );
      });
    }
    headerEl.addEventListener("contextmenu", (e) => {
      var _a;
      e.preventDefault();
      const menu = new import_obsidian4.Menu();
      if (!isNoValue) {
        menu.addItem((item) => {
          item.setTitle("Rename column").setIcon("lucide-pencil").onClick(() => {
            this.startColumnRename(
              titleEl,
              columnName,
              entries,
              countEl,
              addCardHeaderBtn
            );
          });
        });
        menu.addSeparator();
      }
      const currentColor = (_a = this.view.getColumnColor(columnName)) != null ? _a : "";
      menu.addItem((item) => {
        item.setTitle("Change color").setIcon("lucide-palette").onClick(() => {
          new ColorPickerModal(
            this.view.app,
            columnName,
            currentColor,
            (color) => {
              this.view.setColumnColor(columnName, color);
            }
          ).open();
        });
      });
      const currentWipLimit = this.view.getWipLimit(columnName);
      menu.addItem((item) => {
        item.setTitle(
          currentWipLimit !== null ? `WIP limit: ${currentWipLimit}` : "Set WIP limit"
        ).setIcon("lucide-gauge").onClick(() => {
          new WipLimitModal(
            this.view.app,
            columnName,
            currentWipLimit,
            (limit) => {
              this.view.setWipLimit(columnName, limit);
            }
          ).open();
        });
      });
      menu.addSeparator();
      menu.addItem((item) => {
        item.setTitle(
          entries.length > 0 ? `Delete column (${entries.length} card${entries.length > 1 ? "s" : ""} will remain)` : "Delete column"
        ).setIcon("lucide-trash-2").setWarning(true).onClick(() => {
          this.handleDeleteColumn(columnName);
        });
      });
      menu.showAtMouseEvent(e);
    });
    const cardsEl = columnEl.createDiv({ cls: "base-board-cards" });
    visibleCards.forEach((entry) => {
      this.view.cardManager.renderCard(cardsEl, entry, columnName);
    });
  }
  renderAddColumnButton(boardEl) {
    const addBtn = boardEl.createDiv({ cls: "base-board-add-column-btn" });
    (0, import_obsidian4.setIcon)(addBtn.createSpan(), "plus");
    addBtn.createSpan({ text: "Add column" });
    addBtn.addEventListener("click", () => this.promptAddColumn());
  }
  promptAddColumn() {
    new InputModal(
      this.view.app,
      "Add column",
      "Column name\u2026",
      (name) => {
        const columns = this.view.getColumns();
        if (columns.includes(name)) {
          new import_obsidian4.Notice(`Column "${name}" already exists.`);
          return;
        }
        columns.push(name);
        this.view.saveColumns(columns);
        this.view.render();
      }
    ).open();
  }
  handleDeleteColumn(columnName) {
    const columns = this.view.getColumns().filter((c) => c !== columnName);
    this.view.saveColumns(columns);
    this.view.render();
  }
  startColumnRename(titleEl, oldName, entries, countEl, addCardBtn) {
    const input = activeDocument.createElement("input");
    input.type = "text";
    input.value = oldName;
    input.className = "base-board-column-title-input";
    if (countEl) countEl.classList.add("base-board-hidden");
    if (addCardBtn) addCardBtn.classList.add("base-board-hidden");
    const restoreChrome = () => {
      if (countEl) countEl.classList.remove("base-board-hidden");
      if (addCardBtn) addCardBtn.classList.remove("base-board-hidden");
    };
    titleEl.replaceWith(input);
    input.focus();
    input.select();
    let committed = false;
    const commit = () => {
      if (committed) return;
      committed = true;
      const newName = input.value.trim();
      restoreChrome();
      if (newName && newName !== oldName) {
        void this.handleRenameColumn(oldName, newName, entries);
      } else {
        this.view.render();
      }
    };
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        commit();
      } else if (e.key === "Escape") {
        e.preventDefault();
        committed = true;
        restoreChrome();
        this.view.render();
      }
    });
    input.addEventListener("blur", commit);
  }
  async handleRenameColumn(oldName, newName, entries) {
    const columns = this.view.getColumns();
    if (columns.includes(newName)) {
      new import_obsidian4.Notice(`Column "${newName}" already exists.`);
      this.view.render();
      return;
    }
    const groupByProp = this.view.getGroupByProperty();
    await this.view.applyBatchUpdate(async () => {
      const updatedColumns = columns.map((c) => c === oldName ? newName : c);
      this.view.saveColumns(updatedColumns);
      if (groupByProp) {
        const updatePromises = entries.map((entry) => {
          var _a;
          const filePath = (_a = entry.file) == null ? void 0 : _a.path;
          if (!filePath) return Promise.resolve();
          const file = this.view.app.vault.getAbstractFileByPath(filePath);
          if (!file || !(file instanceof import_obsidian4.TFile)) return Promise.resolve();
          return this.view.app.fileManager.processFrontMatter(
            file,
            (fm) => {
              fm[groupByProp] = newName;
            }
          );
        });
        await Promise.all(updatePromises);
      }
    });
  }
};

// src/card.ts
var import_obsidian6 = require("obsidian");

// src/card-detail-modal.ts
var import_obsidian5 = require("obsidian");
var CardDetailModal = class extends import_obsidian5.Modal {
  constructor(app, file, view) {
    super(app);
    this.file = file;
    this.view = view;
  }
  async onOpen() {
    const { contentEl } = this;
    this.modalEl.addClass("base-board-card-modal");
    this.titleEl.empty();
    const actionsEl = contentEl.createDiv({
      cls: "base-board-card-modal-actions"
    });
    new import_obsidian5.ButtonComponent(actionsEl).setButtonText("Open in split pane").setIcon("lucide-columns").onClick(() => {
      this.close();
      const leaf = this.app.workspace.getLeaf("split");
      void leaf.openFile(this.file);
    });
    new import_obsidian5.ButtonComponent(actionsEl).setButtonText("Open in new tab").setIcon("lucide-external-link").onClick(() => {
      this.close();
      const leaf = this.app.workspace.getLeaf("tab");
      void leaf.openFile(this.file);
    });
    new import_obsidian5.ButtonComponent(actionsEl).setButtonText("Edit tags").setIcon("lucide-tags").onClick(() => {
      this.view.tags.promptEditTags(this.file);
    });
    contentEl.createEl("hr", { cls: "base-board-modal-separator" });
    const bodyEl = contentEl.createDiv({ cls: "base-board-card-modal-body" });
    const LeafClass = import_obsidian5.WorkspaceLeaf;
    this.leaf = new LeafClass(this.app);
    await this.leaf.openFile(this.file, { active: false });
    bodyEl.appendChild(this.leaf.view.containerEl);
    this.leaf.view.containerEl.addClass("base-board-rogue-leaf-container");
  }
  onClose() {
    if (this.leaf) {
      this.leaf.detach();
    }
    this.contentEl.empty();
  }
};

// src/card.ts
var IMAGE_EXTENSIONS = /* @__PURE__ */ new Set([
  "apng",
  "avif",
  "bmp",
  "gif",
  "heic",
  "heif",
  "ico",
  "jpeg",
  "jpg",
  "png",
  "svg",
  "webp"
]);
function formatValueForChip(val) {
  var _a;
  if (val instanceof import_obsidian6.DateValue) {
    return val.relative();
  }
  if (val instanceof import_obsidian6.LinkValue) {
    const raw = val.toString();
    const match = raw.match(/^\[\[([^|\]]+)(?:\|([^\]]+))?\]\]$/);
    if (match) {
      const target = match[1];
      const alias = match[2];
      if (alias) return alias;
      const basename = (_a = target.split("/").pop()) != null ? _a : target;
      return basename.replace(/\.md$/, "");
    }
    return raw;
  }
  if (val instanceof import_obsidian6.ListValue) {
    const parts = [];
    const len = val.length();
    for (let i = 0; i < len; i++) {
      const item = val.get(i);
      if (!item || item instanceof import_obsidian6.NullValue || !item.isTruthy()) continue;
      parts.push(formatValueForChip(item));
    }
    return parts.join(", ");
  }
  return val.toString();
}
var FILE_PROPS_TO_SKIP = /* @__PURE__ */ new Set([
  "name",
  "basename",
  "fullname",
  "ext",
  "extension",
  "path",
  "links",
  "backlinks",
  "inlinks",
  "outlinks",
  "embeds",
  "tags"
]);
var CardManager = class {
  constructor(view) {
    this.view = view;
  }
  renderCard(cardsEl, entry, columnName) {
    var _a, _b, _c, _d;
    const filePath = (_b = (_a = entry.file) == null ? void 0 : _a.path) != null ? _b : "";
    const cardEl = cardsEl.createDiv({ cls: "base-board-card" });
    cardEl.setAttr("draggable", "true");
    cardEl.dataset.filePath = filePath;
    cardEl.dataset.columnName = columnName;
    const file = this.view.app.vault.getAbstractFileByPath(filePath);
    const coverProp = this.view.getCardCoverProperty();
    if (file instanceof import_obsidian6.TFile && coverProp) {
      const src = this.getCardCoverSrc(file, coverProp);
      if (src) {
        this.renderCardThumbnail(cardEl, src);
      }
    }
    let dragging = false;
    cardEl.addEventListener("dragstart", () => {
      dragging = true;
    });
    cardEl.addEventListener("dragend", () => {
      window.setTimeout(() => {
        dragging = false;
      }, 0);
    });
    cardEl.addEventListener("click", (e) => {
      if (dragging) return;
      const isAlt = e.altKey;
      const isShift = e.shiftKey;
      const isMod = e.ctrlKey || e.metaKey;
      if ((isAlt || isShift) && !isMod) {
        e.preventDefault();
        this.handleCardSelect(filePath, columnName, isShift);
        return;
      }
      if (this.view.selectedCards.size > 0) {
        this.clearSelection();
        return;
      }
      const file2 = this.view.app.vault.getAbstractFileByPath(filePath);
      if (!(file2 instanceof import_obsidian6.TFile)) return;
      const mod = import_obsidian6.Keymap.isModEvent(e);
      if (mod) {
        e.preventDefault();
        void this.view.app.workspace.getLeaf(mod).openFile(file2);
        return;
      }
      const openBehavior = this.view.getCardOpenBehavior();
      if (openBehavior === "split") {
        if (this.view.detailLeaf && this.view.isLeafAttached(this.view.detailLeaf)) {
          void this.view.detailLeaf.openFile(file2);
        } else {
          this.view.detailLeaf = this.view.app.workspace.getLeaf(
            "split",
            "vertical"
          );
          void this.view.detailLeaf.openFile(file2);
        }
      } else if (openBehavior === "tab") {
        void this.view.app.workspace.getLeaf("tab").openFile(file2);
      } else if (openBehavior === "active") {
        void this.view.app.workspace.getLeaf(false).openFile(file2);
      } else {
        new CardDetailModal(this.view.app, file2, this.view).open();
      }
    });
    cardEl.addEventListener("auxclick", (e) => {
      if (e.button !== 1) return;
      const file2 = this.view.app.vault.getAbstractFileByPath(filePath);
      if (!(file2 instanceof import_obsidian6.TFile)) return;
      void this.view.app.workspace.getLeaf("tab").openFile(file2);
    });
    cardEl.setAttribute("tabindex", "-1");
    cardEl.addEventListener("keydown", (e) => {
      if (e.key === "Escape" && this.view.selectedCards.size > 0) {
        e.preventDefault();
        this.clearSelection();
      }
    });
    cardEl.addEventListener("mouseenter", (evt) => {
      if (!filePath) return;
      this.view.app.workspace.trigger("hover-link", {
        event: evt,
        source: "base-board",
        hoverParent: this.view,
        targetEl: cardEl,
        linktext: filePath
      });
    });
    cardEl.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      const file2 = this.view.app.vault.getAbstractFileByPath(filePath);
      if (!(file2 instanceof import_obsidian6.TFile)) return;
      if (this.view.selectedCards.size > 1 && this.view.selectedCards.has(filePath)) {
        this.showBatchMoveMenu(e);
        return;
      }
      const menu = new import_obsidian6.Menu();
      this.view.app.workspace.trigger(
        "file-menu",
        menu,
        file2,
        "base-board-card",
        this.view.app.workspace.getMostRecentLeaf()
      );
      menu.showAtMouseEvent(e);
    });
    const tagContainerEl = cardEl.createDiv({
      cls: "base-board-tag-container"
    });
    if (file instanceof import_obsidian6.TFile) {
      const fileTags = this.view.tags.extractTagsFromFile(file);
      for (const tag of fileTags) {
        const tagEl = tagContainerEl.createSpan({
          cls: "base-board-card-tag",
          text: tag
        });
        const color = this.view.tags.getColorForTag(tag);
        if (color) {
          tagEl.style.setProperty("--tag-color", color);
          if (relativeLuminance(color) === "dark") {
            tagEl.addClass("base-board-card-tag-light");
          } else {
            tagEl.addClass("base-board-card-tag-dark");
          }
        }
      }
    }
    const titleEl = cardEl.createDiv({ cls: "base-board-card-title" });
    let cardTitle = (_d = (_c = entry.file) == null ? void 0 : _c.basename) != null ? _d : "Untitled";
    const titleProp = this.view.config.get("cardTitleProperty");
    if (titleProp) {
      const propId = titleProp.startsWith("note.") ? titleProp : `note.${titleProp}`;
      const tv = entry.getValue(propId);
      if (tv && !(tv instanceof import_obsidian6.NullValue) && tv.isTruthy()) {
        cardTitle = formatValueForChip(tv);
      }
    }
    titleEl.createSpan({ text: cardTitle });
    const editBtn = cardEl.createDiv({ cls: "base-board-card-edit-btn" });
    (0, import_obsidian6.setIcon)(editBtn, "lucide-pencil");
    editBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      this.showCardActionMenu(editBtn, filePath, titleEl);
    });
    const propsEl = cardEl.createDiv({ cls: "base-board-card-props" });
    const groupByProp = this.view.getGroupByProperty();
    const visibleProps = this.view.config.getOrder();
    const chips = [];
    for (const propId of visibleProps) {
      if (chips.length >= 6) break;
      if (propId.startsWith("file.")) {
        if (FILE_PROPS_TO_SKIP.has(propId.slice(5))) continue;
      }
      const propName = propId.startsWith("note.") ? propId.slice(5) : propId;
      if (groupByProp && propName === groupByProp) continue;
      if (propName === ORDER_PROPERTY) continue;
      const val = entry.getValue(propId);
      if (!val || val instanceof import_obsidian6.NullValue || !val.isTruthy()) continue;
      const display = formatValueForChip(val);
      if (!display) continue;
      chips.push({
        propId,
        displayName: this.view.config.getDisplayName(propId),
        display
      });
    }
    const CHIP_VISIBLE = 4;
    for (let i = 0; i < chips.length && i < CHIP_VISIBLE; i++) {
      const { displayName, display, propId } = chips[i];
      this.renderChip(propsEl, displayName, display, propId);
    }
    let overflowEl = null;
    for (let i = CHIP_VISIBLE; i < chips.length; i++) {
      if (!overflowEl) {
        overflowEl = propsEl.createDiv({
          cls: "base-board-card-chips-overflow"
        });
      }
      const { displayName, display, propId } = chips[i];
      this.renderChip(overflowEl, displayName, display, propId);
    }
    if (overflowEl) {
      const overflowCount = chips.length - CHIP_VISIBLE;
      const toggleBtn = propsEl.createSpan({
        cls: "base-board-card-chip-more"
      });
      toggleBtn.setText(`+${overflowCount} more`);
      toggleBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        const expanded = overflowEl.classList.toggle(
          "base-board-card-chips-overflow--expanded"
        );
        toggleBtn.setText(expanded ? "show less" : `+${overflowCount} more`);
      });
    }
  }
  /** Create a single chip span with label + value inside the given parent. */
  renderChip(parent, label, value, propId) {
    const chip = parent.createSpan({ cls: "base-board-card-chip" });
    if (propId) chip.setAttr("data-property-id", propId);
    chip.createSpan({ text: label, cls: "base-board-chip-label" });
    chip.createSpan({ text: value, cls: "base-board-chip-value" });
    return chip;
  }
  showCardActionMenu(anchorEl, filePath, titleEl) {
    const file = this.view.app.vault.getAbstractFileByPath(filePath);
    if (!file || !(file instanceof import_obsidian6.TFile)) return;
    const menu = new import_obsidian6.Menu();
    menu.addItem((item) => {
      item.setTitle("Edit tags").setIcon("lucide-tags").onClick(() => {
        this.view.tags.promptEditTags(file);
      });
    });
    menu.addItem((item) => {
      item.setTitle("Open").setIcon("lucide-file-text").onClick(() => {
        const openBehavior = this.view.getCardOpenBehavior();
        if (openBehavior === "split") {
          if (this.view.detailLeaf && this.view.isLeafAttached(this.view.detailLeaf)) {
            void this.view.detailLeaf.openFile(file);
          } else {
            this.view.detailLeaf = this.view.app.workspace.getLeaf(
              "split",
              "vertical"
            );
            void this.view.detailLeaf.openFile(file);
          }
        } else if (openBehavior === "tab") {
          void this.view.app.workspace.getLeaf("tab").openFile(file);
        } else if (openBehavior === "active") {
          void this.view.app.workspace.getLeaf(false).openFile(file);
        } else {
          new CardDetailModal(this.view.app, file, this.view).open();
        }
      });
    });
    menu.addItem((item) => {
      item.setTitle("Open in new tab").setIcon("lucide-file-plus").onClick(() => {
        void this.view.app.workspace.getLeaf("tab").openFile(file);
      });
    });
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("Rename").setIcon("lucide-pencil").onClick(() => {
        this.startCardRename(titleEl, file);
      });
    });
    menu.addItem((item) => {
      item.setTitle("Delete").setIcon("lucide-trash-2").onClick(async () => {
        await this.view.app.fileManager.trashFile(file);
        new import_obsidian6.Notice(`Moved "${file.basename}" to trash`);
      });
    });
    const rect = anchorEl.getBoundingClientRect();
    menu.showAtPosition({ x: rect.right, y: rect.bottom });
  }
  startCardRename(titleEl, file) {
    const titleSpan = titleEl.querySelector("span");
    if (!titleSpan) return;
    const input = activeDocument.createElement("input");
    input.type = "text";
    input.value = file.basename;
    input.className = "base-board-card-rename-input";
    titleSpan.replaceWith(input);
    input.focus();
    input.select();
    let committed = false;
    const commit = async () => {
      if (committed) return;
      committed = true;
      const newName = input.value.trim();
      if (newName && newName !== file.basename) {
        const newPath = file.path.replace(
          /[^/]+\.md$/,
          `${sanitizeFilename(newName)}.md`
        );
        try {
          await this.view.app.fileManager.renameFile(file, newPath);
        } catch (err) {
          new import_obsidian6.Notice(`Rename failed: ${String(err)}`);
        }
      }
      this.view.scheduleRender();
    };
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void commit();
      } else if (e.key === "Escape") {
        e.preventDefault();
        committed = true;
        this.view.scheduleRender();
      }
    });
    input.addEventListener("blur", () => {
      void commit();
    });
  }
  startInlineCardCreation(btnEl, columnName, existingCount) {
    var _a;
    const columnEl = btnEl.closest(".base-board-column");
    const cardsEl = (_a = columnEl == null ? void 0 : columnEl.querySelector(".base-board-cards")) != null ? _a : btnEl.parentElement;
    btnEl.classList.add("base-board-hidden");
    const inputWrapper = cardsEl.createDiv({
      cls: "base-board-add-card-input-wrapper"
    });
    const input = inputWrapper.createEl("input", {
      cls: "base-board-add-card-input",
      attr: { type: "text", placeholder: "Card title\u2026" }
    });
    input.focus();
    let committed = false;
    const commit = async () => {
      if (committed) return;
      committed = true;
      const name = input.value.trim();
      inputWrapper.remove();
      btnEl.classList.remove("base-board-hidden");
      if (name) {
        await this.createNewCard(name, columnName, existingCount);
      }
    };
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        void commit();
      } else if (e.key === "Escape") {
        e.preventDefault();
        committed = true;
        inputWrapper.remove();
        btnEl.classList.remove("base-board-hidden");
      }
    });
    input.addEventListener("blur", () => {
      void commit();
    });
  }
  async createNewCard(title, columnName, orderIndex) {
    const groupByProp = this.view.getGroupByProperty();
    if (!groupByProp) {
      new import_obsidian6.Notice("Cannot create card: no group by property configured.");
      return;
    }
    const overrides = (fm) => {
      fm[groupByProp] = columnName;
      fm[ORDER_PROPERTY] = orderIndex;
    };
    try {
      await this.view.createFileForView(title, overrides);
    } catch (err) {
      new import_obsidian6.Notice(`Failed to create card: ${String(err)}`);
    }
  }
  // ---------------------------------------------------------------------------
  //  Multi-select helpers
  // ---------------------------------------------------------------------------
  /**
   * Toggle or range-select a card.
   *
   * - Cmd/Ctrl+click  → toggle this card in/out of the selection
   * - Shift+click     → select a contiguous range from the last-selected card
   *                     to this one (within the same column's DOM order)
   */
  handleCardSelect(filePath, columnName, isShift) {
    const sel = this.view.selectedCards;
    if (isShift && sel.size > 0) {
      const columnEl = this.view.containerEl.querySelector(
        `[data-column-name="${CSS.escape(columnName)}"]`
      );
      if (columnEl) {
        const cardEls = Array.from(
          columnEl.querySelectorAll(".base-board-card")
        );
        const paths = cardEls.map((el) => {
          var _a;
          return (_a = el.dataset.filePath) != null ? _a : "";
        });
        const clickedIdx = paths.indexOf(filePath);
        const lastIdx = paths.reduceRight((found, p, i) => {
          if (found !== -1) return found;
          return sel.has(p) ? i : -1;
        }, -1);
        if (clickedIdx !== -1 && lastIdx !== -1) {
          const [from, to] = [
            Math.min(clickedIdx, lastIdx),
            Math.max(clickedIdx, lastIdx)
          ];
          for (let i = from; i <= to; i++) {
            if (paths[i]) sel.add(paths[i]);
          }
        } else {
          sel.add(filePath);
        }
      }
    } else {
      if (sel.has(filePath)) {
        sel.delete(filePath);
      } else {
        sel.add(filePath);
      }
    }
    this.view.containerEl.querySelectorAll(".base-board-card").forEach((el) => {
      var _a;
      if (sel.has((_a = el.dataset.filePath) != null ? _a : "")) {
        el.addClass("base-board-card--selected");
      } else {
        el.removeClass("base-board-card--selected");
      }
    });
  }
  clearSelection() {
    this.view.selectedCards.clear();
    this.view.containerEl.querySelectorAll(".base-board-card--selected").forEach((el) => el.removeClass("base-board-card--selected"));
  }
  /**
   * Show a "Move to…" context menu for the current multi-selection.
   * Uses the same `applyBatchUpdate` + `processFrontMatter` pattern as
   * the single-card drag/drop to stay consistent.
   */
  showBatchMoveMenu(e) {
    const selectedPaths = Array.from(this.view.selectedCards);
    const groupByProp = this.view.getGroupByProperty();
    if (!groupByProp) return;
    const columns = this.view.getColumns();
    const menu = new import_obsidian6.Menu();
    menu.addItem((item) => {
      item.setTitle(`Move ${selectedPaths.length} cards to\u2026`).setDisabled(true);
    });
    menu.addSeparator();
    for (const col of columns) {
      menu.addItem((item) => {
        item.setTitle(col).onClick(() => {
          void this.moveBatchToColumn(selectedPaths, col, groupByProp);
        });
      });
    }
    menu.showAtMouseEvent(e);
  }
  async moveBatchToColumn(filePaths, targetColumn, groupByProp) {
    await this.view.applyBatchUpdate(async () => {
      const updates = filePaths.map((fp, i) => {
        const file = this.view.app.vault.getAbstractFileByPath(fp);
        if (!file || !(file instanceof import_obsidian6.TFile)) return Promise.resolve();
        return this.view.app.fileManager.processFrontMatter(
          file,
          (fm) => {
            fm[groupByProp] = targetColumn;
            fm[ORDER_PROPERTY] = i;
          }
        );
      });
      await Promise.all(updates);
    });
    this.clearSelection();
    new import_obsidian6.Notice(
      `Moved ${filePaths.length} card${filePaths.length > 1 ? "s" : ""} to "${targetColumn}"`
    );
  }
  getCardCoverSrc(file, coverPropName) {
    var _a;
    if (coverPropName === "__proto__" || coverPropName === "constructor") {
      return null;
    }
    const cache = this.view.app.metadataCache.getFileCache(file);
    const rawValue = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a[coverPropName];
    if (!rawValue) return null;
    if (typeof rawValue !== "string" && typeof rawValue !== "number")
      return null;
    if (typeof rawValue === "string" && /^https?:\/\//i.test(rawValue)) {
      return rawValue;
    }
    const cleanPath = String(rawValue).replace(/^!?\[\[(.*?)\]\]$/, "$1").split("|")[0].split("#")[0].trim();
    if (!cleanPath) return null;
    const resolved = this.view.app.metadataCache.getFirstLinkpathDest(
      cleanPath,
      file.path
    );
    if (resolved instanceof import_obsidian6.TFile && IMAGE_EXTENSIONS.has(resolved.extension.toLowerCase())) {
      return this.view.app.vault.getResourcePath(resolved);
    }
    return null;
  }
  renderCardThumbnail(cardEl, src) {
    const thumbEl = activeDocument.createElement("div");
    thumbEl.className = "base-board-card-thumbnail";
    thumbEl.createEl("img", {
      cls: "base-board-card-thumbnail-img",
      attr: { src, loading: "lazy" }
    }).addEventListener("error", () => {
      thumbEl.remove();
      cardEl.removeClass("base-board-card--has-thumbnail");
    });
    cardEl.prepend(thumbEl);
    cardEl.addClass("base-board-card--has-thumbnail");
  }
};

// src/kanban-view.ts
var KanbanView = class extends import_obsidian7.BasesView {
  constructor(controller, scrollEl, plugin) {
    super(controller);
    this.type = "kanban";
    // Required by HoverParent — Obsidian manages the popover lifecycle.
    this.hoverPopover = null;
    this.currentGroups = [];
    /** Prevent re-renders while we batch-update frontmatter. */
    this.isUpdating = false;
    /** Track if Bases fired onDataUpdated while we were updating. */
    this.pendingRender = false;
    /** True until the first successful render completes. */
    this.isFirstRender = true;
    /** Debounce timer for render calls. */
    this.renderTimer = null;
    /** Currently selected card file paths (for batch operations) */
    this.selectedCards = /* @__PURE__ */ new Set();
    this.detailLeaf = null;
    this.scrollEl = scrollEl;
    this.plugin = plugin;
    this.containerEl = scrollEl.createDiv({ cls: "base-board-container" });
    this.tags = new Tags(this);
    this.cardManager = new CardManager(this);
    this.columnManager = new ColumnManager(this);
    this.dragDropManager = new DragDropManager(this.app, {
      onCardDrop: (filePath, targetColumn, orderedPaths) => this.handleCardDrop(filePath, targetColumn, orderedPaths),
      onColumnReorder: (orderedNames) => this.handleColumnReorder(orderedNames),
      getSelectedCards: () => this.selectedCards
    });
  }
  onload() {
  }
  onunload() {
    this.dragDropManager.destroy();
    if (this.renderTimer) window.clearTimeout(this.renderTimer);
  }
  focus() {
    this.containerEl.focus({ preventScroll: true });
  }
  onDataUpdated() {
    if (this.isUpdating) {
      this.pendingRender = true;
      return;
    }
    this.scheduleRender();
  }
  /**
   * Run a batch of state updates without triggering intermediate re-renders.
   * Defers rendering until the entire batch is complete.
   */
  async applyBatchUpdate(updateFn) {
    this.isUpdating = true;
    this.pendingRender = false;
    try {
      await updateFn();
    } finally {
      this.isUpdating = false;
    }
    if (this.pendingRender) {
      this.pendingRender = false;
      this.scheduleRender();
    }
  }
  static getViewOptions() {
    return [
      {
        type: "group",
        displayName: "Display",
        items: [
          {
            key: CONFIG_KEY_OPEN_BEHAVIOR,
            type: "dropdown",
            displayName: "Open card in",
            default: "active",
            options: {
              active: "Active pane / tab",
              modal: "Floating modal",
              split: "Split to the right",
              tab: "New tab"
            }
          },
          {
            key: CONFIG_KEY_COVER_PROPERTY,
            type: "text",
            displayName: "Cover property",
            default: "cover",
            placeholder: "E.g. cover"
          }
        ]
      }
    ];
  }
  // ---------------------------------------------------------------------------
  //  Base identity
  // ---------------------------------------------------------------------------
  /**
   * Build a stable, unique identifier for this board view.
   *
   * Uses the view's display name (unique within a .base file) combined with
   * the groupBy property.  If neither is available we fall back to a hash
   * derived from the file paths currently in the dataset so that column
   * configs never collide across different boards.
   */
  getBaseId() {
    var _a, _b, _c, _d, _e, _f, _g;
    const viewName = (_b = (_a = this.config) == null ? void 0 : _a.name) != null ? _b : "";
    const groupBy = (_c = this.getGroupByProperty()) != null ? _c : "";
    let basePath = "";
    const entries = (_e = (_d = this.data) == null ? void 0 : _d.data) != null ? _e : [];
    if (entries.length > 0) {
      const firstPath = (_g = (_f = entries[0].file) == null ? void 0 : _f.path) != null ? _g : "";
      const lastSlash = firstPath.lastIndexOf("/");
      basePath = lastSlash > 0 ? firstPath.substring(0, lastSlash) : "";
    }
    return `${basePath}::${viewName}::${groupBy}`;
  }
  // ---------------------------------------------------------------------------
  //  Helpers
  // ---------------------------------------------------------------------------
  /**
   * Return the frontmatter property name used for groupBy (e.g. "status").
   *
   * The Bases engine stores this in the view config as a BasesPropertyId
   * like "note.status".  We strip the "note." prefix so the result is
   * directly usable as a frontmatter key.
   *
   * Note: `BasesViewConfig.get()` only retrieves custom options registered
   * via `BasesViewRegistration.options`.  The `groupBy` setting is a
   * built-in structural property on the config object, so we access it
   * directly from the config's internal representation.
   */
  getGroupByProperty() {
    var _a;
    const cfg = this.config;
    const groupBy = cfg == null ? void 0 : cfg.groupBy;
    if (groupBy == null ? void 0 : groupBy.property) {
      const raw = groupBy.property;
      return raw.startsWith("note.") ? raw.slice(5) : raw;
    }
    const fromGet = (_a = cfg == null ? void 0 : cfg.get) == null ? void 0 : _a.call(cfg, "groupBy");
    if (fromGet == null ? void 0 : fromGet.property) {
      const raw = fromGet.property;
      return raw.startsWith("note.") ? raw.slice(5) : raw;
    }
    return null;
  }
  getCardOpenBehavior() {
    var _a;
    const val = (_a = this.config) == null ? void 0 : _a.get(CONFIG_KEY_OPEN_BEHAVIOR);
    if (val === "modal" || val === "split" || val === "tab") return val;
    return "active";
  }
  getCardCoverProperty() {
    var _a;
    const val = (_a = this.config) == null ? void 0 : _a.get(CONFIG_KEY_COVER_PROPERTY);
    if (val === void 0 || val === null) {
      return "cover";
    }
    return typeof val === "string" && val.trim() !== "" ? val.trim() : null;
  }
  isLeafAttached(leaf) {
    let found = false;
    this.app.workspace.iterateAllLeaves((l) => {
      if (l === leaf) found = true;
    });
    return found;
  }
  getColumnColors() {
    var _a;
    const raw = (_a = this.config) == null ? void 0 : _a.get(CONFIG_KEY_COLUMN_COLORS);
    return raw && typeof raw === "object" ? raw : {};
  }
  getColumnColor(columnName) {
    var _a;
    const customColors = this.getColumnColors();
    return (_a = customColors[columnName]) != null ? _a : null;
  }
  setColumnColor(columnName, color) {
    var _a;
    const colors = this.getColumnColors();
    if (color) {
      colors[columnName] = color;
    } else {
      delete colors[columnName];
    }
    (_a = this.config) == null ? void 0 : _a.set(CONFIG_KEY_COLUMN_COLORS, colors);
    this.scheduleRender();
  }
  // ---------------------------------------------------------------------------
  //  WIP Limits
  // ---------------------------------------------------------------------------
  getWipLimits() {
    var _a;
    const raw = (_a = this.config) == null ? void 0 : _a.get(CONFIG_KEY_WIP_LIMITS);
    return raw && typeof raw === "object" ? raw : {};
  }
  getWipLimit(columnName) {
    const limits = this.getWipLimits();
    const val = limits[columnName];
    return typeof val === "number" && val > 0 ? val : null;
  }
  setWipLimit(columnName, limit) {
    var _a;
    const limits = this.getWipLimits();
    if (limit !== null && limit > 0) {
      limits[columnName] = limit;
    } else {
      delete limits[columnName];
    }
    (_a = this.config) == null ? void 0 : _a.set(CONFIG_KEY_WIP_LIMITS, limits);
    this.scheduleRender();
  }
  getColumnName(key) {
    if (key === void 0 || key === null || key instanceof import_obsidian7.NullValue) {
      return NO_VALUE_COLUMN;
    }
    if (typeof key === "object" && key !== null) {
      if ("value" in key) {
        const val = key.value;
        return String(val);
      }
      return String(key);
    }
    if (typeof key === "string") return key;
    if (typeof key === "number" || typeof key === "boolean") return String(key);
    return "";
  }
  /**
   * Read kanban_order from metadataCache (more reliable than entry.values
   * since the Bases engine may not expose all properties).
   */
  getFileOrder(filePath) {
    var _a;
    const file = this.app.vault.getAbstractFileByPath(filePath);
    if (!file || !(file instanceof import_obsidian7.TFile)) return Infinity;
    const cache = this.app.metadataCache.getFileCache(file);
    const order = (_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a[ORDER_PROPERTY];
    if (typeof order === "number") return order;
    return Infinity;
  }
  // ---------------------------------------------------------------------------
  //  Column config  (dual-layer: .base file via config API + plugin data.json)
  // ---------------------------------------------------------------------------
  /**
   * Read the persisted column order.
   *
   * Priority:
   *  1. View-level config stored inside the .base file (via BasesViewConfig)
   *  2. Legacy plugin data.json (for backwards-compat with existing boards)
   *  3. Fall back to whatever columns the data naturally produces
   *
   * Any columns present in the live data but missing from the stored list
   * are appended at the end so they are never silently hidden.
   */
  getColumns() {
    var _a, _b;
    const fromConfig = (_a = this.config) == null ? void 0 : _a.get(CONFIG_KEY_COLUMNS);
    const fromPlugin = this.plugin.getColumnConfig(this.getBaseId());
    const rawStored = (fromConfig == null ? void 0 : fromConfig.length) ? fromConfig : ((_b = fromPlugin == null ? void 0 : fromPlugin.columns) == null ? void 0 : _b.length) ? fromPlugin.columns : null;
    const stored = rawStored ? rawStored.map((col) => col === "" ? NO_VALUE_COLUMN : col) : null;
    const dataColumns = this.currentGroups.map(
      (g) => this.getColumnName(g.key)
    );
    if (stored && stored.length > 0) {
      const result = [...stored];
      for (const col of dataColumns) {
        if (!result.includes(col)) {
          result.push(col);
        }
      }
      return result;
    }
    return dataColumns;
  }
  getGroupForColumn(columnName) {
    for (const group of this.currentGroups) {
      if (this.getColumnName(group.key) === columnName) {
        return group;
      }
    }
    return null;
  }
  // ---------------------------------------------------------------------------
  //  Rendering
  // ---------------------------------------------------------------------------
  render() {
    var _a, _b, _c, _d, _e, _f;
    this.selectedCards.clear();
    const prevBoardEl = this.containerEl.querySelector(".base-board-board");
    const savedScrollLeft = (_a = prevBoardEl == null ? void 0 : prevBoardEl.scrollLeft) != null ? _a : 0;
    const savedScrollTop = this.scrollEl.scrollTop;
    const savedColumnScrolls = {};
    if (prevBoardEl) {
      prevBoardEl.querySelectorAll(".base-board-column").forEach((col) => {
        const name = col.dataset.columnName;
        const cardsEl = col.querySelector(".base-board-cards");
        if (name && cardsEl) {
          savedColumnScrolls[name] = cardsEl.scrollTop;
        }
      });
    }
    this.containerEl.empty();
    const groupedData = (_c = (_b = this.data) == null ? void 0 : _b.groupedData) != null ? _c : [];
    const hasGroupBy = groupedData.length > 1 || groupedData.length === 1 && groupedData[0].key !== void 0 && !(groupedData[0].key instanceof import_obsidian7.NullValue);
    const stored = (_f = (_d = this.config) == null ? void 0 : _d.get(CONFIG_KEY_COLUMNS)) != null ? _f : (_e = this.plugin.getColumnConfig(this.getBaseId())) == null ? void 0 : _e.columns;
    const hasStoredColumns = stored && stored.length > 0;
    const shouldShowPlaceholder = !hasGroupBy && groupedData.length <= 1 && !hasStoredColumns;
    if (shouldShowPlaceholder) {
      const msgEl = this.containerEl.createDiv({
        cls: "base-board-placeholder"
      });
      (0, import_obsidian7.setIcon)(
        msgEl.createSpan({ cls: "base-board-placeholder-icon" }),
        "lucide-kanban"
      );
      msgEl.createEl("p", {
        text: 'Set "group by" in the sort menu to organize cards into columns.'
      });
      return;
    }
    this.currentGroups = groupedData;
    const columns = this.getColumns();
    const boardEl = this.containerEl.createDiv({ cls: "base-board-board" });
    if (this.isFirstRender) {
      boardEl.addClass("base-board-board--animate");
      this.isFirstRender = false;
    }
    this.tags.renderFilterBar(this.containerEl);
    columns.forEach((columnName, idx) => {
      const group = this.getGroupForColumn(columnName);
      this.columnManager.renderColumn(boardEl, columnName, group, idx);
    });
    this.columnManager.renderAddColumnButton(boardEl);
    this.dragDropManager.initBoard(boardEl);
    const hasColumnScrolls = Object.keys(savedColumnScrolls).some(
      (k) => savedColumnScrolls[k] > 0
    );
    if (savedScrollLeft > 0 || savedScrollTop > 0 || hasColumnScrolls) {
      window.requestAnimationFrame(() => {
        boardEl.scrollLeft = savedScrollLeft;
        this.scrollEl.scrollTop = savedScrollTop;
        boardEl.querySelectorAll(".base-board-column").forEach((col) => {
          const name = col.dataset.columnName;
          const cardsEl = col.querySelector(".base-board-cards");
          const scroll = name ? savedColumnScrolls[name] : void 0;
          if (cardsEl && scroll != null && scroll > 0) {
            cardsEl.scrollTop = scroll;
          }
        });
      });
    }
  }
  // ---------------------------------------------------------------------------
  //  Column & Filter management helpers
  // ---------------------------------------------------------------------------
  handleColumnReorder(orderedNames) {
    this.saveColumns(orderedNames);
    this.render();
  }
  /**
   * Persist the column list.
   *
   * Writes to two locations for compatibility:
   *  - BasesViewConfig (stored inside the .base file itself — portable)
   *  - Plugin data.json (legacy, kept so older board setups still work)
   */
  saveColumns(columns) {
    var _a;
    const toSave = columns.map((col) => col === NO_VALUE_COLUMN ? "" : col);
    (_a = this.config) == null ? void 0 : _a.set(CONFIG_KEY_COLUMNS, toSave);
    void this.plugin.saveColumnConfig(this.getBaseId(), { columns });
  }
  // ---------------------------------------------------------------------------
  //  Card drop handler (column move + reordering)
  // ---------------------------------------------------------------------------
  async handleCardDrop(filePath, targetColumnName, orderedPaths) {
    const groupByProp = this.getGroupByProperty();
    if (!groupByProp) return;
    const selectedSnapshot = new Set(this.selectedCards);
    const isMultiDrag = selectedSnapshot.size > 1 && selectedSnapshot.has(filePath);
    const otherSelected = isMultiDrag ? Array.from(selectedSnapshot).filter(
      (p) => p !== filePath && !orderedPaths.includes(p)
    ) : [];
    const fullOrderedPaths = [...orderedPaths];
    if (otherSelected.length > 0) {
      const dropIdx = fullOrderedPaths.indexOf(filePath);
      const insertAt = dropIdx !== -1 ? dropIdx + 1 : fullOrderedPaths.length;
      fullOrderedPaths.splice(insertAt, 0, ...otherSelected);
    }
    await this.applyBatchUpdate(async () => {
      const pathsToMove = isMultiDrag ? [filePath, ...otherSelected] : [filePath];
      const movePromises = pathsToMove.map((fp) => {
        const file = this.app.vault.getAbstractFileByPath(fp);
        if (!file || !(file instanceof import_obsidian7.TFile)) return Promise.resolve();
        const sourceColumn = this.getCardSourceColumn(fp);
        if (sourceColumn === targetColumnName) return Promise.resolve();
        return this.app.fileManager.processFrontMatter(
          file,
          (fm) => {
            if (targetColumnName === NO_VALUE_COLUMN) {
              delete fm[groupByProp];
            } else {
              fm[groupByProp] = targetColumnName;
            }
          }
        );
      });
      await Promise.all(movePromises);
      const orderPromises = fullOrderedPaths.map((cardPath, i) => {
        const file = this.app.vault.getAbstractFileByPath(cardPath);
        if (!file || !(file instanceof import_obsidian7.TFile)) return Promise.resolve();
        return this.app.fileManager.processFrontMatter(
          file,
          (fm) => {
            fm[ORDER_PROPERTY] = i;
          }
        );
      });
      await Promise.all(orderPromises);
    });
    this.scheduleRender();
  }
  /** Debounced render — coalesces multiple calls into one. */
  scheduleRender() {
    if (this.renderTimer) window.clearTimeout(this.renderTimer);
    this.renderTimer = window.setTimeout(() => {
      this.renderTimer = null;
      this.render();
    }, 50);
  }
  getCardSourceColumn(filePath) {
    var _a;
    for (const group of this.currentGroups) {
      for (const entry of group.entries) {
        if (((_a = entry.file) == null ? void 0 : _a.path) === filePath) {
          return this.getColumnName(group.key);
        }
      }
    }
    return null;
  }
};

// src/folder-rename.ts
var FILTER_PATH_ARG_PATTERN = /(\(\s*(["']))(.*?)(\2\s*\))/g;
function updateBaseFolderReferences(content, oldPath, newPath) {
  if (!oldPath || oldPath === newPath) return null;
  let changed = false;
  const updated = content.replace(
    FILTER_PATH_ARG_PATTERN,
    (match, pre, _quote, path, post) => {
      let newInnerPath = null;
      if (path === oldPath) {
        newInnerPath = newPath;
      } else if (path.startsWith(oldPath + "/")) {
        newInnerPath = newPath + path.slice(oldPath.length);
      }
      if (newInnerPath === null) return match;
      changed = true;
      return pre + newInnerPath + post;
    }
  );
  return changed ? updated : null;
}

// src/main.ts
var DEFAULT_DATA = {
  columnConfigs: {}
};
var BaseBoardPlugin = class extends import_obsidian8.Plugin {
  constructor() {
    super(...arguments);
    this.data_ = DEFAULT_DATA;
    /** Folder rename mappings collected during one rename burst, pending flush. */
    this.pendingFolderRenames = [];
    /** Debounce timer that flushes pendingFolderRenames once the burst settles. */
    this.folderRenameFlushTimer = null;
  }
  async onload() {
    await this.loadPluginData();
    this.registerBasesView("kanban", {
      name: "Kanban",
      icon: "lucide-kanban",
      factory: (controller, containerEl) => new KanbanView(controller, containerEl, this),
      options: () => KanbanView.getViewOptions()
    });
    this.addCommand({
      id: "create-board",
      name: "Create new board",
      callback: () => {
        new CreateBoardModal(this.app, (config) => {
          void this.createBoard(config);
        }).open();
      }
    });
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        this.handleFolderRename(file, oldPath);
      })
    );
  }
  onunload() {
    if (this.folderRenameFlushTimer !== null) {
      window.clearTimeout(this.folderRenameFlushTimer);
    }
  }
  // -- Folder rename sync -----------------------------------------------------
  /**
   * When a folder is renamed or moved, rewrite any .base board filter that
   * pointed at the old path so the board keeps working without a manual edit.
   *
   * To avoid race condition, burst of renaming events are collected, and once
   * a timeout is reached we flush and modify the path mappings in .base
   */
  handleFolderRename(file, oldPath) {
    const timeOut = 250;
    if (!(file instanceof import_obsidian8.TFolder)) return;
    const newPath = file.path;
    if (newPath === oldPath) return;
    this.pendingFolderRenames.push({ oldPath, newPath });
    if (this.folderRenameFlushTimer !== null) {
      window.clearTimeout(this.folderRenameFlushTimer);
    }
    this.folderRenameFlushTimer = window.setTimeout(() => {
      this.folderRenameFlushTimer = null;
      void this.flushFolderRenames();
    }, timeOut);
  }
  /** Apply all pending folder-rename mappings to every .base file. */
  async flushFolderRenames() {
    const renames = this.pendingFolderRenames;
    this.pendingFolderRenames = [];
    if (renames.length === 0) return;
    const baseFiles = this.app.vault.getFiles().filter((f) => f.extension === "base");
    for (const baseFile of baseFiles) {
      try {
        let content = await this.app.vault.read(baseFile);
        let changed = false;
        for (const { oldPath, newPath } of renames) {
          const updated = updateBaseFolderReferences(content, oldPath, newPath);
          if (updated !== null) {
            content = updated;
            changed = true;
          }
        }
        if (changed) {
          await this.app.vault.modify(baseFile, content);
        }
      } catch (err) {
        console.error(
          `Base Board: failed to update folder references in "${baseFile.path}"`,
          err
        );
      }
    }
  }
  // -- Board scaffolding ------------------------------------------------------
  async createBoard(config) {
    const { name, folder, groupBy } = config;
    const vault = this.app.vault;
    const safeFolder = folder.replace(/[\\:*?"<>|]/g, "");
    const tasksFolder = `${safeFolder}/Tasks`;
    if (!vault.getAbstractFileByPath(safeFolder)) {
      await vault.createFolder(safeFolder);
    }
    if (!vault.getAbstractFileByPath(tasksFolder)) {
      await vault.createFolder(tasksFolder);
    }
    const basePath = `${safeFolder}/${name}.base`;
    if (vault.getAbstractFileByPath(basePath)) {
      new import_obsidian8.Notice(`A board already exists at "${basePath}".`);
      return;
    }
    const baseContent = [
      `filters:`,
      `  and:`,
      `    - file.inFolder("${tasksFolder}")`,
      `views:`,
      `  - type: kanban`,
      `    name: ${name}`,
      `    groupBy:`,
      `      property: note.${groupBy}`,
      `      direction: DESC`,
      `    order:`,
      `      - file.name`,
      `      - note.${groupBy}`,
      ``
    ].join("\n");
    await vault.create(basePath, baseContent);
    const sampleTasks = [
      {
        title: "Plan project",
        value: "To Do",
        order: 0,
        tags: ["planning"]
      },
      {
        title: "Research and discovery",
        value: "To Do",
        order: 1,
        tags: ["research"]
      },
      {
        title: "Build first feature",
        value: "In Progress",
        order: 0,
        tags: ["feature"]
      },
      {
        title: "Fix onboarding bug",
        value: "In Progress",
        order: 1,
        tags: ["bug"]
      },
      {
        title: "Write documentation",
        value: "Done",
        order: 0,
        tags: ["docs"]
      }
    ];
    for (const task of sampleTasks) {
      const safeName = sanitizeFilename(task.title);
      const taskPath = `${tasksFolder}/${safeName}.md`;
      if (!vault.getAbstractFileByPath(taskPath)) {
        const tagsLine = task.tags.length > 0 ? `tags:
${task.tags.map((t) => `  - ${t}`).join("\n")}` : "";
        const content = [
          "---",
          `${groupBy}: ${task.value}`,
          `kanban_order: ${task.order}`,
          tagsLine,
          "---",
          "",
          `# ${task.title}`,
          ""
        ].filter((line) => line !== "").join("\n");
        await vault.create(taskPath, content);
      }
    }
    const file = vault.getAbstractFileByPath(basePath);
    if (file instanceof import_obsidian8.TFile) {
      void this.app.workspace.getLeaf(false).openFile(file);
      new import_obsidian8.Notice(`Board "${name}" created!`);
    }
  }
  // -- Column config helpers --------------------------------------------------
  getColumnConfig(baseId) {
    var _a;
    return (_a = this.data_.columnConfigs[baseId]) != null ? _a : null;
  }
  async saveColumnConfig(baseId, config) {
    this.data_.columnConfigs[baseId] = config;
    await this.savePluginData();
  }
  // -- Persistence ------------------------------------------------------------
  async loadPluginData() {
    const saved = await this.loadData();
    this.data_ = Object.assign({}, DEFAULT_DATA, saved != null ? saved : {});
    if (!this.data_.columnConfigs) this.data_.columnConfigs = {};
  }
  async savePluginData() {
    await this.saveData(this.data_);
  }
};

/* nosourcemap */